name: Update README with Issue Body

on:
  issues:
    types:
      - opened

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Check if issue creator is justyntemme@gmail.com
        id: creator_check
        run: |
          if [[ "${{ github.actor }}" == "justyntemme" ]]; then
            echo "is_authorized=true" >> $GITHUB_OUTPUT
          else
            echo "is_authorized=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop if issue creator is not authorized
        if: steps.creator_check.outputs.is_authorized == 'false'
        run: |
          echo "Issue creator is not authorized. Skipping update."
          exit 0

      - name: Check if issue title starts with [Automated]
        id: title_check
        run: |
          if [[ "${{ github.event.issue.title }}" == "[Automated]"* ]]; then
            echo "is_automated=true" >> $GITHUB_OUTPUT
          else
            echo "is_automated=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop if not an [Automated] issue
        if: steps.title_check.outputs.is_automated == 'false'
        run: |
          echo "Issue title does not start with [Automated]. Skipping update."
          exit 0

      - name: Append issue body to README.md
        env:
          TEXT: ${{ github.event.issue.body }}
        run: |
          echo "${TEXT}" >> README.md
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README.md with issue body from #${{ github.event.issue.number }}"
          git push origin main
